Added automatic secure boot key genearation when they are not there
AP-Sensing/PhotonPonyOS pull request #12
Opened 2023-11-08 14:53 UTC by maxeljaxel

### Previous
Composing wasn't possible when there were no secure boot keys.

###  Solution
Check if the secure boot keys exist, if not the ephemeral keys will be generated.

2023-11-09 06:43 UTC, COM8 requested changes
Looks good, but I left a few improvement suggestions.

2023-11-09 06:43 UTC, COM8 commented on justfile
>      chown -R ${user}:${user} iso release repo
Instead of creating empty directories and then setting the access rights, please only call `chown` for directories that exist.

2023-11-09 06:43 UTC, COM8 commented on justfile
> +    emailAddress         = info@apsensing.com
```suggestion
    commonName           = Ephemeral Platform Key
    emailAddress         = not-a-vald-production-key@example.com
```

2023-11-09 06:43 UTC, COM8 commented on justfile
> +        -keyout secureBoot/PK.key -out secureBoot/PK.pem
```suggestion
    openssl req -x509 -sha256 -days 5490 -outform PEM -config secureBoot/cfg/PK.cfg -keyout secureBoot/PK.key -out secureBoot/PK.pem
```

I prefer single line statements since we have the hspace for it. Please fix it for all others as well.

2023-11-09 06:43 UTC, COM8 commented on justfile
> +    cp secureBoot/cfg/PK.cfg secureBoot/
We do not need a copy. Please update all paths so there is only a single `PK.cfg` located in `secureBoot/PK.cfg`.

2023-11-10 14:51 UTC, maxeljaxel commented on justfile
>      chown -R ${user}:${user} iso release repo
deleted create-folders. chown is now only called on directories that exist

2023-11-10 14:51 UTC, maxeljaxel commented on justfile
> +    emailAddress         = info@apsensing.com
Changed this

2023-11-10 14:51 UTC, maxeljaxel commented on justfile
> +        -keyout secureBoot/PK.key -out secureBoot/PK.pem
Done

2023-11-10 14:51 UTC, maxeljaxel commented on justfile
> +    cp secureBoot/cfg/PK.cfg secureBoot/
Fixed all paths

2023-11-15 13:30 UTC, COM8 approved these changes

2023-11-15 13:30 UTC, merged