Added a Gitlab CI automation
AP-Sensing/PhotonPonyOS pull request #19
Opened 2023-12-06 07:44 UTC by maxeljaxel

###Gitlab CI Automation
Added a Gitlab CI automation that compos and lorax the build and export the public signature key.

2023-12-11 07:39 UTC, COM8 requested changes

2023-12-11 07:39 UTC, COM8 commented on .gitlab-ci.yml
> +
```suggestion

```

2023-12-11 07:39 UTC, COM8 commented on .gitlab-ci.yml
> +stages:
```suggestion
######################################

stages:
```

2023-12-11 07:39 UTC, COM8 commented on .gitlab-ci.yml
> +    - dnf install -y just ostree lorax rpm-ostree jq pip selinux-policy selinux-policy-targeted policycoreutils openssl git akmods kmodtool
Is `akmods` really required for this?

2023-12-11 07:39 UTC, COM8 commented on .gitlab-ci.yml
> +      #- "iso/KS-Fedora*"
What's about those artifacts? Does exporting them work?

2023-12-11 07:39 UTC, COM8 commented on README.md
> +```
Is this all that is needed for building it inside a gitlab runner?

2023-12-11 07:39 UTC, COM8 commented on README.md
> +The loop module has to be loaded on the Host of the GitLab-Runner
```suggestion
The loop module has to be loaded on the host of the GitLab-Runner.
This can be done via:
...

The GitLab tomel file (path to the file) also needs no be changed and `privileged` mode needs to be enabled.
Why? Because XYZ
```

Please add documentation for how to load it.

2023-12-11 07:39 UTC, COM8 commented on README.md
> +
```suggestion

```

2023-12-11 10:15 UTC, maxeljaxel commented on README.md
> +The loop module has to be loaded on the Host of the GitLab-Runner
Spelling corrections and explanation done

2023-12-13 06:12 UTC, maxeljaxel commented on .gitlab-ci.yml
> +    - dnf install -y just ostree lorax rpm-ostree jq pip selinux-policy selinux-policy-targeted policycoreutils openssl git akmods kmodtool
Its's not

2023-12-13 06:15 UTC, maxeljaxel commented on README.md
> +```
The rest is private information like url, id, token etc.

2023-12-15 07:24 UTC, COM8 requested changes
Made some final wording changes. Other than that we are ready to go.

2023-12-15 07:24 UTC, COM8 commented on README.md
> +The Gitlab configuration file can be found at /etc/gitlab-runner/config.toml
```suggestion
The Gitlab configuration file can be found at `/etc/gitlab-runner/config.toml`.
```

2023-12-15 07:24 UTC, COM8 commented on README.md
> +Since building the image requires read/write permissions on mounted devices the docker needs to be privileged.
```suggestion
Since building the image requires read/write permissions on mounted devices (e.g. `/dev/loop0`), docker images using it need to be marked as `privileged`.
```

2023-12-16 09:38 UTC, COM8 approved these changes
Now we are ready to go. Thanks!

2023-12-16 09:38 UTC, merged